image: node:latest
variables:
  CI_IMG: "\"${CI_REGISTRY_IMAGE}:latest\""     # TODO: Configure uni docker registry variables
  TP_URL: "${CI_PROJECT_NAMESPACE}.bham.team"
  TP_CONTACT: "${GITLAB_USER_EMAIL}"

stages:                                         # List of stages for jobs, and their order of execution
  - fetch_dependencies
  - check
  - build
  - test
  - package
  - deploy

npm_install:
  stage: fetch_dependencies
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR    # Run npm ci and maintain cache for each branch
    paths:
      - node_modules/
  script:
    - npm clean-install
  only:
    changes:
      - package-lock.json                       # Only re-fetch if dependencies were added/removed since last cache

eslint:
  stage: check
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - npm i
    - echo "${CI_REGISTRY_IMAGE} ${CI_REGISTRY_USER} ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}"
    - npx eslint --ext .ts,.tsx client/         # Lint the client
    - npx eslint --ext .ts server/              # Lint the server

tsc:
  stage: build
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - npx tsc                                   # Build the client using Vite
    - npx vite build                            # and the server using esbuild
    - npx esbuild ./server/main.ts --tsconfig=tsconfig.server.json --outfile=dist/server.cjs --bundle --platform=node --minify
  artifacts:
    paths:
      - dist                                    # Upload ./dist to artefacts
    expire_in: 1 day

docker:
  stage: package
  services:
    - docker:dind
  variables:
    DOCKER_HOST: 'tcp://docker:2375'
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - echo "Containerising application..."
    - docker build -f .cd/Dockerfile .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}:latest

deploy-job:
  stage: deploy
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  image: alpine:latest
  before_script: 
   - chmod og= $SSH_KEY
   - apk update && apk add openssh-client
   - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $VM_USER@$VM "docker compose -f ~/team-project-deployment/.cd/app.yml  down || true"
   - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $VM_USER@$VM "docker rm -f $(docker ps -a -q) || true"
   - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $VM_USER@$VM "docker volume rm $(docker volume ls -q) || true"
   - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $VM_USER@$VM "rm -rf ~/team-project-deployment || true"
   - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $VM_USER@$VM "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
   - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $VM_USER@$VM "docker pull ${CI_REGISTRY_IMAGE}:latest"
  script:
   - scp -o StrictHostKeyChecking=no -i $SSH_KEY -r . $VM_USER@$VM:~/team-project-deployment 
   - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $VM_USER@$VM "sed -i '5s|teamproject|$CI_IMG|' ~/team-project-deployment/.cd/app.yml"
   - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $VM_USER@$VM "docker compose -f ~/team-project-deployment/.cd/app.yml up -d"

