version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - ~/volumes/db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  teamproject-app:
    image: git.cs.bham.ac.uk:5050/team-projects-2022-23/team29-22:latest
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
