import {
  CreationOptional,
  DataTypes,
  InferAttributes,
  InferCreationAttributes,
  Model,
} from "sequelize";

export class Accommodation extends Model<
  InferAttributes<Accommodation>,
  InferCreationAttributes<Accommodation>
> {
  // Unique integer auto-generated by the db
  declare accommId: CreationOptional<number>;
  // Accommodation name
  declare name: string;

  // Latitude/longitude (roughly) locating the accommodation (in decimal degrees)
  declare latitude: number;
  declare longitude: number;
}

export const init = sequelize =>
  Accommodation.init(
    {
      accommId: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      name: {
        type: DataTypes.TEXT,
        allowNull: false,
        unique: true,
      },
      latitude: {
        type: DataTypes.DOUBLE,
        allowNull: false,
      },
      longitude: {
        type: DataTypes.DOUBLE,
        allowNull: false,
      },
    },
    { modelName: "Accommodation", freezeTableName: true, sequelize }
  );
