import {
  CreationOptional,
  DataTypes,
  InferAttributes,
  InferCreationAttributes,
  Model,
} from "sequelize";

export class Accommodation extends Model<
  InferAttributes<Accommodation>,
  InferCreationAttributes<Accommodation>
> {
  // Unique integer auto-generated by the db
  declare accommId: CreationOptional<number>;
  // Accommodation name
  declare name: string;
}

export const init = sequelize =>
  Accommodation.init(
    {
      accommId: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      name: {
        type: DataTypes.TEXT,
        allowNull: false,
        unique: true,
      },
    },
    { sequelize }
  );
