import {
  CreationOptional,
  DataTypes,
  InferAttributes,
  InferCreationAttributes,
  Model,
} from "sequelize";

export class Course extends Model<
  InferAttributes<Course>,
  InferCreationAttributes<Course>
> {
  // Unique integer auto-generated by the db
  declare courseId: CreationOptional<number>;
  // Course name
  declare name: string;
}

export const init = sequelize =>
  Course.init(
    {
      courseId: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      name: {
        type: DataTypes.TEXT,
        allowNull: false,
        unique: true,
      },
    },
    { sequelize }
  );
