import {
  CreationOptional,
  DataTypes,
  InferAttributes,
  InferCreationAttributes,
  Model,
} from "sequelize";

export class FileStorage extends Model<
  InferAttributes<FileStorage>,
  InferCreationAttributes<FileStorage>
> {
  // Unique integer auto-generated by the db
  declare fileId: CreationOptional<number>;
  // Relative path to file
  declare relPath: string;

  // Original name of file
  declare name: string;
}

export const init = sequelize =>
  FileStorage.init(
    {
      fileId: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      name: {
        type: DataTypes.TEXT,
        allowNull: false,
      },
      relPath: {
        type: DataTypes.TEXT,
        allowNull: false,
        unique: true,
      },
    },
    { modelName: "FileStorage", freezeTableName: true, sequelize }
  );
