import {
  CreationOptional,
  DataTypes,
  InferAttributes,
  InferCreationAttributes,
  Model,
} from "sequelize";

export class Module extends Model<
  InferAttributes<Module>,
  InferCreationAttributes<Module>
> {
  // Unique integer auto-generated by the db
  declare moduleId: CreationOptional<number>;
  // Module name
  declare name: string;
  // Module description
  declare description: string;
}

export const init = sequelize =>
  Module.init(
    {
      moduleId: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      name: {
        type: DataTypes.TEXT,
        allowNull: false,
        unique: true,
      },
      description: {
        type: DataTypes.TEXT,
        allowNull: false,
      },
    },
    { modelName: "Module", freezeTableName: true, sequelize }
  );
