import {
  CreationOptional,
  DataTypes,
  InferAttributes,
  InferCreationAttributes,
  Model,
} from "sequelize";
import { User } from "./user.model.js";

export class RichText extends Model<
  InferAttributes<RichText>,
  InferCreationAttributes<RichText>
> {
  // Unique integer auto-generated by the db
  declare widgetId: CreationOptional<number>;
  // User who owns the widget
  declare user: number;
  // Title
  declare title: string;
  // Content
  declare content: string;
}

export const init = sequelize =>
  RichText.init(
    {
      widgetId: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      user: {
        type: DataTypes.INTEGER,
        allowNull: false,
      },
      title: {
        type: DataTypes.TEXT,
        allowNull: false,
      },
      content: {
        type: DataTypes.TEXT,
        allowNull: false,
      },
    },
    { sequelize }
  );
