import {
  BelongsToGetAssociationMixin,
  BelongsToSetAssociationMixin,
  CreationOptional,
  ForeignKey,
  Model,
} from "sequelize";
import { User } from "./user.model.js";

export abstract class Widget<
  InferredAttributes extends {},
  InferredCreationAttributes extends {}
> extends Model<InferredAttributes, InferredCreationAttributes> {
  // Unique integer auto-generated by the db
  declare widgetId: CreationOptional<number>;
  // User who owns the widget
  declare user: ForeignKey<User["userId"]>;

  // Association mixins
  declare getOwner: BelongsToGetAssociationMixin<User>;
  declare setOwner: BelongsToSetAssociationMixin<User, number>;
}
